default_context:
  project_name: 'action_smr'
  project_slug: 'action_smr'
  domain_main: 'action_smr.com'
  domain_staging: 'stag.action_smr.com'
  docker_swarm_stack_name_main: 'action_smr-com'
  docker_swarm_stack_name_staging: 'stag-action_smr-com'
  secret_key: 'masonlin'
  first_superuser: 'admin@action_smr.com'
  first_superuser_password: 'masonlin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.action_smr.com", "https://stag.action_smr.com", "https://action_smr.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@action_smr.com'
  postgres_password: 'masonlin'
  pgadmin_default_user: 'admin@action_smr.com'
  pgadmin_default_user_password: 'masonlin'
  traefik_constraint_tag: 'action_smr.com'
  traefik_constraint_tag_staging: 'stag.action_smr.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:masonlin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
