# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vcosmos_pb2 as vcosmos__pb2


class ImpacketStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.wmiexec = channel.unary_unary(
                '/vcosmos.Impacket/wmiexec',
                request_serializer=vcosmos__pb2.CmdRequest.SerializeToString,
                response_deserializer=vcosmos__pb2.CmdReply.FromString,
                )


class ImpacketServicer(object):
    """Missing associated documentation comment in .proto file."""

    def wmiexec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImpacketServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'wmiexec': grpc.unary_unary_rpc_method_handler(
                    servicer.wmiexec,
                    request_deserializer=vcosmos__pb2.CmdRequest.FromString,
                    response_serializer=vcosmos__pb2.CmdReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vcosmos.Impacket', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Impacket(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def wmiexec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vcosmos.Impacket/wmiexec',
            vcosmos__pb2.CmdRequest.SerializeToString,
            vcosmos__pb2.CmdReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
