# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vcosmos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvcosmos.proto\x12\x07vcosmos\"\x19\n\nCmdRequest\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\">\n\x08\x43mdReply\x12\x12\n\nreturncode\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t2?\n\x08Impacket\x12\x33\n\x07wmiexec\x12\x13.vcosmos.CmdRequest\x1a\x11.vcosmos.CmdReply\"\x00\x62\x06proto3')



_CMDREQUEST = DESCRIPTOR.message_types_by_name['CmdRequest']
_CMDREPLY = DESCRIPTOR.message_types_by_name['CmdReply']
CmdRequest = _reflection.GeneratedProtocolMessageType('CmdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CMDREQUEST,
  '__module__' : 'vcosmos_pb2'
  # @@protoc_insertion_point(class_scope:vcosmos.CmdRequest)
  })
_sym_db.RegisterMessage(CmdRequest)

CmdReply = _reflection.GeneratedProtocolMessageType('CmdReply', (_message.Message,), {
  'DESCRIPTOR' : _CMDREPLY,
  '__module__' : 'vcosmos_pb2'
  # @@protoc_insertion_point(class_scope:vcosmos.CmdReply)
  })
_sym_db.RegisterMessage(CmdReply)

_IMPACKET = DESCRIPTOR.services_by_name['Impacket']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CMDREQUEST._serialized_start=26
  _CMDREQUEST._serialized_end=51
  _CMDREPLY._serialized_start=53
  _CMDREPLY._serialized_end=115
  _IMPACKET._serialized_start=117
  _IMPACKET._serialized_end=180
# @@protoc_insertion_point(module_scope)
